<a href="https://colab.research.google.com/github/Tanish-Sarkar/Elite-Transformers/blob/main/Module0%20-%20PyTorch%20Ramp-Up/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals** — `we will learn on the go`

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### **Intro about Tensors**

Creating tensors

In [2]:
# scaler
scaler = torch.tensor(7)
scaler


tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                        [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [10]:
MATRIX[0,0]

tensor(7)

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2],
                        [4,5]]])
TENSOR

tensor([[[1, 2],
         [4, 5]]])

In [12]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 2, 2])


### Random Tensors

In [13]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7601, 0.5727, 0.4283, 0.4565],
        [0.1785, 0.5441, 0.5480, 0.1032],
        [0.1165, 0.2475, 0.3362, 0.4961]])

In [14]:
print(random_tensor.ndim)
print(random_tensor.shape)

2
torch.Size([3, 4])


In [15]:
random_tensor = torch.rand(1, 5, 6)
random_tensor

tensor([[[0.1482, 0.7204, 0.7170, 0.9750, 0.0068, 0.3135],
         [0.0524, 0.3547, 0.2454, 0.4386, 0.0255, 0.6479],
         [0.4393, 0.0318, 0.7179, 0.4120, 0.0355, 0.9115],
         [0.0381, 0.1844, 0.2964, 0.3059, 0.4631, 0.5932],
         [0.2189, 0.1211, 0.9978, 0.0274, 0.6282, 0.0760]]])

In [16]:
# Create a random tensor woth similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [17]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.3659, 0.6792, 0.3920, 0.3109],
        [0.3901, 0.8280, 0.1280, 0.9958],
        [0.2504, 0.3840, 0.0526, 0.6930]])

In [19]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### **Creating a range of tensors and tensor-like**

In [22]:
# use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
one_to_th = torch.arange(start=1, end=1000, step=69)
one_to_th

tensor([  1,  70, 139, 208, 277, 346, 415, 484, 553, 622, 691, 760, 829, 898,
        967])

In [24]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [25]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor.dtype

torch.float16

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [30]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [31]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Get infomation from tensor

In [33]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.2091, 0.2392, 0.2780, 0.3450],
        [0.6759, 0.3420, 0.0612, 0.5285],
        [0.5868, 0.4285, 0.0099, 0.0755]])

In [34]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu



**Manipulating Tensors (tensor operations)**

Tensor opertions include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [35]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [36]:
# add 10 in it
tensor + 10

tensor([11, 12, 13])

In [37]:
# subtracting 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [38]:
# multiple 10 in tensor
tensor * 10

tensor([10, 20, 30])

In [39]:
# trying out the function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [40]:
torch.add(tensor, 10)

tensor([11, 12, 13])


**Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:**

* Element-wise multiplication
* Matrix mutliplication (dot product)

In [41]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
_2d_tensor = torch.rand(size=(3,2))
print(_2d_tensor, "*", _2d_tensor)
print(f"Equals: {_2d_tensor * _2d_tensor}")

tensor([[0.0480, 0.0889],
        [0.6045, 0.5151],
        [0.4375, 0.8063]]) * tensor([[0.0480, 0.0889],
        [0.6045, 0.5151],
        [0.4375, 0.8063]])
Equals: tensor([[0.0023, 0.0079],
        [0.3654, 0.2653],
        [0.1914, 0.6501]])



**`_2d_tensor has a shape of (3, 2), so multiplying it by itself (3, 2) * (3, 2) is not possible because 2 (columns of first) does not equal 3 (rows of second). To fix this, you can transpose one of the tensors.`**


In [44]:
torch.matmul(_2d_tensor, _2d_tensor.T)


tensor([[0.0102, 0.0748, 0.0927],
        [0.0748, 0.6307, 0.6798],
        [0.0927, 0.6798, 0.8416]])

sample testing

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.44 ms, sys: 56 µs, total: 1.49 ms
Wall time: 1.6 ms


In [46]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 538 µs, sys: 0 ns, total: 538 µs
Wall time: 618 µs


tensor(14)

### **One of the most common errors in deep learning: shape errors**

In [66]:

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)


## ERROR WILL OCCUR

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [50]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## **Finding the min, max, mean, sum, etc (tensor aggregation)**

In [51]:
x = torch.arange(0,101,10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [52]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [53]:
torch.max(x), x.max()

(tensor(100), tensor(100))

In [57]:
torch.mean(x)  # error will occur

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
##  Input dtype must be either a floating point or complex dtype.

torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [59]:
# Find the sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))

## **Finding the positional min and max**

In [62]:
# Find the index where the minimum value is present
x.argmin()

tensor(0)

In [63]:
# Find the index where the maximum value is present
x.argmax()

tensor(10)

In [64]:
x[0]

tensor(0)

In [65]:
x[10]

tensor(100)

## **Reshaping, stacking, squeezing and unsqueezing tensors**
- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all `1`dimensions from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [67]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [83]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
'''
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape
'''

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [76]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [78]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

### **Squeeze/Unsqueeze and Permute**

In [81]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [86]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [89]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 103, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: \t{x_permuted.shape}') # [colour_channels, height, width]

Previous shape: torch.Size([224, 103, 3])
New shape: 	torch.Size([3, 224, 103])


In [90]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))