<a href="https://colab.research.google.com/github/Tanish-Sarkar/Elite-Transformers/blob/main/Module0%20-%20PyTorch%20Ramp-Up/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals** — `we will learn on the go`

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### **Intro about Tensors**

Creating tensors

In [2]:
# scaler
scaler = torch.tensor(7)
scaler


tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                        [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [10]:
MATRIX[0,0]

tensor(7)

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2],
                        [4,5]]])
TENSOR

tensor([[[1, 2],
         [4, 5]]])

In [12]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 2, 2])


### Random Tensors

In [13]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9826, 0.0414, 0.0415, 0.3633],
        [0.2610, 0.0285, 0.3140, 0.4726],
        [0.3059, 0.7570, 0.0193, 0.0525]])

In [14]:
print(random_tensor.ndim)
print(random_tensor.shape)

2
torch.Size([3, 4])


In [15]:
random_tensor = torch.rand(1, 5, 6)
random_tensor

tensor([[[0.7089, 0.7075, 0.2518, 0.6059, 0.5663, 0.4786],
         [0.4579, 0.0746, 0.7680, 0.5170, 0.1098, 0.3500],
         [0.4903, 0.6072, 0.6889, 0.5271, 0.6837, 0.0834],
         [0.4907, 0.2261, 0.9708, 0.7308, 0.6745, 0.6235],
         [0.2821, 0.5157, 0.5955, 0.8459, 0.1356, 0.5570]]])

In [16]:
# Create a random tensor woth similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.5950, 0.3688, 0.4044, 0.2361],
        [0.5877, 0.2383, 0.4738, 0.2409],
        [0.5279, 0.6531, 0.5325, 0.6042]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32