<a href="https://colab.research.google.com/github/Tanish-Sarkar/Elite-Transformers/blob/main/Module0%20-%20PyTorch%20Ramp-Up/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals** — `we will learn on the go`

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### **Intro about Tensors**

Creating tensors

In [2]:
# scaler
scaler = torch.tensor(7)
scaler


tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                        [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [10]:
MATRIX[0,0]

tensor(7)

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2],
                        [4,5]]])
TENSOR

tensor([[[1, 2],
         [4, 5]]])

In [12]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 2, 2])


### Random Tensors

In [13]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8011, 0.8452, 0.3856, 0.0410],
        [0.9251, 0.4066, 0.2860, 0.2747],
        [0.4198, 0.9090, 0.0866, 0.3406]])

In [14]:
print(random_tensor.ndim)
print(random_tensor.shape)

2
torch.Size([3, 4])


In [15]:
random_tensor = torch.rand(1, 5, 6)
random_tensor

tensor([[[0.0655, 0.1915, 0.7935, 0.1829, 0.0826, 0.2648],
         [0.2774, 0.3858, 0.1788, 0.4513, 0.5903, 0.6285],
         [0.8404, 0.7431, 0.2078, 0.1431, 0.6234, 0.4326],
         [0.3876, 0.0344, 0.1357, 0.2424, 0.3076, 0.4952],
         [0.5541, 0.9600, 0.1235, 0.1481, 0.8576, 0.2562]]])

In [16]:
# Create a random tensor woth similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [17]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.4390, 0.1272, 0.6091, 0.0640],
        [0.0469, 0.1005, 0.4787, 0.6902],
        [0.7542, 0.8962, 0.2236, 0.9143]])

In [19]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### **Creating a range of tensors and tensor-like**

In [22]:
# use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
one_to_th = torch.arange(start=1, end=1000, step=69)
one_to_th

tensor([  1,  70, 139, 208, 277, 346, 415, 484, 553, 622, 691, 760, 829, 898,
        967])

In [24]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [25]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor.dtype

torch.float16

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [30]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [31]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Get infomation from tensor

In [33]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.5373, 0.9707, 0.4487, 0.4951],
        [0.6571, 0.4671, 0.9472, 0.6701],
        [0.4336, 0.6885, 0.3026, 0.5049]])

In [34]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu



**Manipulating Tensors (tensor operations)**

Tensor opertions include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [35]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [36]:
# add 10 in it
tensor + 10

tensor([11, 12, 13])

In [37]:
# subtracting 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [38]:
# multiple 10 in tensor
tensor * 10

tensor([10, 20, 30])

In [40]:
# trying out the function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])


**Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:**

* Element-wise multiplication
* Matrix mutliplication (dot product)

In [42]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
_2d_tensor = torch.rand(size=(3,2))
print(_2d_tensor, "*", _2d_tensor)
print(f"Equals: {_2d_tensor * _2d_tensor}")

tensor([[0.9757, 0.8676],
        [0.5470, 0.6931],
        [0.6485, 0.4816]]) * tensor([[0.9757, 0.8676],
        [0.5470, 0.6931],
        [0.6485, 0.4816]])
Equals: tensor([[0.9519, 0.7527],
        [0.2992, 0.4803],
        [0.4206, 0.2320]])



**`_2d_tensor has a shape of (3, 2), so multiplying it by itself (3, 2) * (3, 2) is not possible because 2 (columns of first) does not equal 3 (rows of second). To fix this, you can transpose one of the tensors.`**


In [47]:
torch.matmul(_2d_tensor, _2d_tensor.T)


tensor([[1.7046, 1.1350, 1.0506],
        [1.1350, 0.7796, 0.6885],
        [1.0506, 0.6885, 0.6525]])

sample testing

In [49]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.9 ms, sys: 0 ns, total: 1.9 ms
Wall time: 1.85 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 314 µs, sys: 937 µs, total: 1.25 ms
Wall time: 975 µs


tensor(14)

### **One of the most common errors in deep learning: shape errors**

In [51]:

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [54]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [55]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## **Finding the min, max, mean, sum, etc (tensor aggregation)**

In [59]:
x = torch.arange(0,101,10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [60]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [68]:
torch.max(x), x.max()

(tensor(100), tensor(100))

In [62]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [69]:
##  Input dtype must be either a floating point or complex dtype.

torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [72]:
# Find the sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))