<a href="https://colab.research.google.com/github/Tanish-Sarkar/Elite-Transformers/blob/main/Module0%20-%20PyTorch%20Ramp-Up/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
x

tensor([[0.6888, 0.5851, 0.4279, 0.8152, 0.9743, 0.8056, 0.0725],
        [0.9402, 0.4944, 0.1175, 0.3388, 0.3920, 0.4616, 0.9967],
        [0.3759, 0.0699, 0.8006, 0.4623, 0.5289, 0.2709, 0.5625],
        [0.5242, 0.3521, 0.7161, 0.2703, 0.8293, 0.2719, 0.1430],
        [0.3004, 0.4649, 0.6241, 0.0227, 0.8293, 0.5037, 0.2632],
        [0.3469, 0.4338, 0.8958, 0.8291, 0.3438, 0.6051, 0.5190],
        [0.2443, 0.5612, 0.2231, 0.3163, 0.2328, 0.8795, 0.5097]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
y = torch.rand(1,7).T
# Perform matrix multiplication
torch.matmul(x,y)

tensor([[2.1238],
        [1.5974],
        [1.3864],
        [1.4983],
        [1.4110],
        [1.7757],
        [1.2957]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(7,7)

# Matrix multiply tensors
torch.matmul(tensor_1, tensor_2)


tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752],
        [1.5323, 1.5229, 1.2803, 1.3610, 0.9783, 1.3436, 1.0728],
        [1.9851, 1.2829, 1.9461, 1.6327, 1.6470, 1.8897, 1.0188],
        [1.6047, 1.9098, 2.3681, 2.3476, 1.6475, 1.9148, 1.4521],
        [1.4985, 0.9676, 1.6055, 1.1853, 1.1255, 1.4089, 0.5297],
        [1.4340, 1.2833, 2.1648, 2.2554, 1.3629, 1.6467, 1.0185],
        [0.9212, 1.1111, 1.4061, 1.7023, 1.3085, 1.4995, 0.7890]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')

# Create two random tensors on GPU
tensor_A = torch.rand(2,3).to(device)
tensor_B = torch.rand(2,3).to(device)

tensor_A, tensor_B


Device: cuda


(tensor([[0.4820, 0.8198, 0.9971],
         [0.6984, 0.5675, 0.8352]], device='cuda:0'),
 tensor([[0.2056, 0.5932, 0.1123],
         [0.1535, 0.2417, 0.7262]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.6974, 0.9962],
         [0.5741, 0.8509]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
max = torch.max(tensor_C)
# Find min
min = torch.min(tensor_C)

max, min

(tensor(0.9962, device='cuda:0'), tensor(0.5741, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
from ast import arg
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)

arg_max, arg_min

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
torch.manual_seed(42)

# Create random tensor
x = torch.rand(1,1,1,10)

# Remove single dimensions
x_squeezed = x.squeeze()

# Print out tensors and their shapes
print(f'x: {x}, shape: {x.shape}')
print(f'x_squeezed: {x_squeezed}, shape: {x_squeezed.shape}')

x: tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
           0.9408, 0.1332]]]]), shape: torch.Size([1, 1, 1, 10])
x_squeezed: tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332]), shape: torch.Size([10])
