<a href="https://colab.research.google.com/github/Tanish-Sarkar/Elite-Transformers/blob/main/Module0%20-%20PyTorch%20Ramp-Up/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals** — `we will learn on the go`

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### **Intro about Tensors**

Creating tensors

In [2]:
# scaler
scaler = torch.tensor(7)
scaler


tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                        [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [10]:
MATRIX[0,0]

tensor(7)

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2],
                        [4,5]]])
TENSOR

tensor([[[1, 2],
         [4, 5]]])

In [12]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 2, 2])


### Random Tensors

In [13]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8011, 0.8452, 0.3856, 0.0410],
        [0.9251, 0.4066, 0.2860, 0.2747],
        [0.4198, 0.9090, 0.0866, 0.3406]])

In [14]:
print(random_tensor.ndim)
print(random_tensor.shape)

2
torch.Size([3, 4])


In [15]:
random_tensor = torch.rand(1, 5, 6)
random_tensor

tensor([[[0.0655, 0.1915, 0.7935, 0.1829, 0.0826, 0.2648],
         [0.2774, 0.3858, 0.1788, 0.4513, 0.5903, 0.6285],
         [0.8404, 0.7431, 0.2078, 0.1431, 0.6234, 0.4326],
         [0.3876, 0.0344, 0.1357, 0.2424, 0.3076, 0.4952],
         [0.5541, 0.9600, 0.1235, 0.1481, 0.8576, 0.2562]]])

In [16]:
# Create a random tensor woth similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [17]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.4390, 0.1272, 0.6091, 0.0640],
        [0.0469, 0.1005, 0.4787, 0.6902],
        [0.7542, 0.8962, 0.2236, 0.9143]])

In [19]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### **Creating a range of tensors and tensor-like**

In [22]:
# use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
one_to_th = torch.arange(start=1, end=1000, step=69)
one_to_th

tensor([  1,  70, 139, 208, 277, 346, 415, 484, 553, 622, 691, 760, 829, 898,
        967])

In [24]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [25]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor.dtype

torch.float16

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [30]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [31]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Get infomation from tensor

In [33]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.5373, 0.9707, 0.4487, 0.4951],
        [0.6571, 0.4671, 0.9472, 0.6701],
        [0.4336, 0.6885, 0.3026, 0.5049]])

In [34]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
