<a href="https://colab.research.google.com/github/Tanish-Sarkar/Elite-Transformers/blob/main/Module0%20-%20PyTorch%20Ramp-Up/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals** — `we will learn on the go`

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### **Intro about Tensors**

Creating tensors

In [2]:
# scaler
scaler = torch.tensor(7)
scaler


tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                        [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [10]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [15]:
MATRIX[0,0]

tensor(7)

In [17]:
# Tensor
TENSOR = torch.tensor([[[1,2],
                        [4,5]]])
TENSOR

tensor([[[1, 2],
         [4, 5]]])

In [18]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 2, 2])


### Random Tensors

In [21]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1025, 0.9976, 0.4452, 0.5042],
        [0.0300, 0.4349, 0.3278, 0.8204],
        [0.5226, 0.7721, 0.3214, 0.5413]])